Date check and sanitisation

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -246,6 +246,13 @@ COLABFOLD_USE_TEMPLATES="<%= context.colabfold_use_templates %>"
 ESMFOLD_RECYCLES="<%= context.esmfold_num_recycles %>"
 BOLTZ_USE_POTENTIALS="<%= context.boltz_use_potentials %>"
 
+if [ -n "${AF2_TEMPLATE_DATE}" ]; then
+    if ! [[ "${AF2_TEMPLATE_DATE}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || ! date -d "${AF2_TEMPLATE_DATE}" "+%Y-%m-%d" >/dev/null 2>&1; then
+        echo "ERROR: AF2 Max Template Date must be a valid date in YYYY-MM-DD format."
+        exit 1
+    fi
+fi
+
 if [ "<%= context.full_dbs %>" == "full" ];
 then
     FULL_DB="true"
